### ISSUE TITLE
Renderbugs when using animated blocks

### ISSUE THREAD

**Issue by DragonDev1906** [DragonDev1906/Minecraft-Overviewer#15]

**Comment by Tirpitz93** [comment]
See warped and crimson stems for examples
![test](https://user-images.githubusercontent.com/6187560/77604419-5c78d400-6f0a-11ea-8877-aca4344e10a9.png)

**Comment by Tirpitz93** [comment]
Temporary fix in place.
would be nice to use a random frame from the animation for each instance of the block.

**Comment by Tirpitz93** [comment]
For enhancement see #14 
closing issue as Bug is fixed for solid blocks
